language: haskell

before_install:
  # Install some dependencies from source
  - cabal install cabal-meta cabal-src

  # Try installing some of the build-deps with apt-get for speed
  - ./tools/travis-cabal-apt-install --only-dependencies --force-reinstall $mode

install:
  - cabal-meta install $mode

env:
  - mode="--enable-tests"

