language: haskell

before_install:
  # Update index.
  - cabal update

  # Fetch the latest feldspar-language from github
  - git clone -v -b master https://github.com/Feldspar/feldspar-language

  # Try installing some of the build-deps with apt-get for speed
  #- ./tools/travis-cabal-apt-install --only-dependencies --force-reinstall

install:
  - cabal install $mode feldspar-language/ ./

env:
  - mode="--enable-tests"

