language: haskell

before_install:
  # Update index.
  - cabal update

  # Install some dependencies from source
  - ./tools/travis-cabal-apt-install cabal-meta cabal-src

  # Try installing some of the build-deps with apt-get for speed
  - ./tools/travis-cabal-apt-install --only-dependencies --force-reinstall

install:
  - cabal-meta install $mode

env:
  - mode="--enable-tests"

