language: haskell

before_install:
  # Fetch the latest feldspar-language from github
  - git clone -v -b master https://github.com/Feldspar/feldspar-language
  - echo "Using feldspar-language from "
  - (cd feldspar-language && git rev-parse HEAD)

  # Try installing some of the build-deps with apt-get for speed
  # - ./tools/travis-cabal-apt-install $mode feldspar-language/ ./
  - cabal install tasty feldspar-language/ ./ --constraint="stm > 2.3"

